"""
AutoDev Agent - FastAPI Application

Provides:
- Dashboard
- Task execution
- Project listing
- Project details
- Project file viewing
- Project ZIP downloads
- Project deletion
- Legacy generated-file endpoints
- Task history
"""

from pathlib import Path
import re
import shutil
import time

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from pydantic import BaseModel, Field

from agent.planner import create_plan

from agent.executor import (
    execute_plan,
    PROJECTS_DIR,
    GENERATED_DIR,
)

from agent.logger import (
    log,
    get_logs,
    clear_logs,
)

from agent.storage import get_generated_file


# ============================================================
# BASE PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

DASHBOARD_FILE = BASE_DIR / "dashboard.html"


# ============================================================
# OPTIONAL HISTORY MODULE
# ============================================================

try:
    from agent.history import (
        create_task_record,
        get_history,
        get_task,
        clear_history,
    )

except ImportError:

    create_task_record = None
    get_history = None
    get_task = None
    clear_history = None


# ============================================================
# APP
# ============================================================

app = FastAPI(
    title="AutoDev Agent",
    description=(
        "Autonomous AI software development agent with "
        "project generation, test generation and self-repair."
    ),
    version="3.0.0",
)


# ============================================================
# REQUEST MODEL
# ============================================================

class TaskRequest(BaseModel):

    task: str = Field(
        ...,
        min_length=1,
        description="Task for AutoDev Agent",
    )

    inputs: dict = Field(
        default_factory=dict
    )


# ============================================================
# PROJECT FILE FILTERING
# ============================================================

# These directories are generated by Python, package managers,
# IDEs, Git, or development tooling. They should NOT appear in
# the AutoDev project browser.

IGNORED_PROJECT_DIRS = {
    ".git",
    ".github",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".coverage",
    ".idea",
    ".vscode",
    ".venv",
    "venv",
    "env",
    "node_modules",
}


# Binary/generated Python artifacts.

IGNORED_PROJECT_SUFFIXES = {
    ".pyc",
    ".pyo",
    ".pyd",
}


IGNORED_PROJECT_FILES = {
    ".DS_Store",
    "Thumbs.db",
}


def is_displayable_project_file(
    path: Path,
) -> bool:
    """
    Determine whether a project file should be visible
    in the AutoDev dashboard.

    This prevents binary/cache artifacts such as:

        __pycache__/main.cpython-314.pyc

    from being displayed as source code.
    """

    if path.name in IGNORED_PROJECT_FILES:
        return False

    if path.suffix.lower() in IGNORED_PROJECT_SUFFIXES:
        return False

    if any(
        part in IGNORED_PROJECT_DIRS
        for part in path.parts
    ):
        return False

    return True


# ============================================================
# PROJECT NAME
# ============================================================

def safe_project_name(
    value: str,
) -> str:

    cleaned = re.sub(
        r"[^A-Za-z0-9\_-]+",
        "_",
        str(
            value
            or "AutoDev_Project"
        ),
    ).strip("_")

    return (
        cleaned[:80]
        or "AutoDev_Project"
    )


# ============================================================
# PROJECT WORKSPACE RESOLUTION
# ============================================================

def resolve_project_workspace(
    workspace_name: str,
) -> Path | None:

    if not workspace_name:
        return None

    safe_name = Path(
        workspace_name
    ).name

    if safe_name != workspace_name:
        return None

    path = PROJECTS_DIR / safe_name

    if (
        not path.exists()
        or not path.is_dir()
    ):
        return None

    return path


# ============================================================
# PROJECT ZIP RESOLUTION
# ============================================================

def resolve_project_zip(
    workspace_name: str,
) -> Path | None:

    if not workspace_name:
        return None

    safe_name = Path(
        workspace_name
    ).name

    if safe_name != workspace_name:
        return None

    path = (
        PROJECTS_DIR
        / f"{safe_name}.zip"
    )

    if (
        not path.exists()
        or not path.is_file()
    ):
        return None

    return path


# ============================================================
# PROJECT FILE RESOLUTION
# ============================================================

def resolve_project_file(
    workspace_name: str,
    file_path: str,
) -> Path | None:

    workspace = resolve_project_workspace(
        workspace_name
    )

    if workspace is None:
        return None

    normalized = (
        str(file_path)
        .replace("\\", "/")
        .lstrip("/")
    )

    if not normalized:
        return None

    candidate = (
        workspace / normalized
    ).resolve()

    try:

        candidate.relative_to(
            workspace.resolve()
        )

    except ValueError:

        return None

    if (
        not candidate.exists()
        or not candidate.is_file()
    ):
        return None

    # Never expose generated/binary artifacts.
    relative = candidate.relative_to(
        workspace
    )

    if not is_displayable_project_file(
        relative
    ):
        return None

    return candidate


# ============================================================
# DASHBOARD
# ============================================================

@app.get(
    "/dashboard",
    response_class=HTMLResponse,
)
def dashboard():

    if not DASHBOARD_FILE.exists():

        raise HTTPException(
            status_code=404,
            detail=(
                "dashboard.html not found."
            ),
        )

    return HTMLResponse(
        DASHBOARD_FILE.read_text(
            encoding="utf-8"
        )
    )


# Root opens dashboard.

@app.get(
    "/",
    response_class=HTMLResponse,
)
def root():

    return dashboard()


# ============================================================
# RUN TASK
# ============================================================

@app.post("/run-task")
def run_task(
    request: TaskRequest,
):

    start_time = time.perf_counter()

    clear_logs()

    plan = None
    result = None
    task_id = None

    try:

        log(
            "🧠 AutoDev task received."
        )

        log(
            f"📌 Task: {request.task}"
        )

        # ----------------------------------------------------
        # PHASE 1: PLANNING
        # ----------------------------------------------------

        plan = create_plan(
            request.task,
            request.inputs,
        )

        # ----------------------------------------------------
        # PHASE 2+:
        # TEST GENERATION
        # EXECUTION
        # AUTONOMOUS REPAIR
        # ----------------------------------------------------

        result = execute_plan(
            plan=plan,
            inputs=request.inputs,
            task=request.task,
        )

        duration = (
            time.perf_counter()
            - start_time
        )

        status = (
            "success"
            if result.get("success")
            else "error"
        )

        workspace_name = result.get(
            "workspace_name"
        )

        zip_file = result.get(
            "zip_file"
        )

        zip_url = (
            f"/download-project/"
            f"{workspace_name}"
            if (
                workspace_name
                and zip_file
            )
            else None
        )

        project_url = (
            f"/projects/"
            f"{workspace_name}"
            if workspace_name
            else None
        )

        # ----------------------------------------------------
        # HISTORY
        # ----------------------------------------------------

        if create_task_record:

            try:

                history_record = (
                    create_task_record(
                        task=request.task,
                        status=status,
                        plan=plan,
                        logs=get_logs(),
                        result=result,
                        generated_file=workspace_name,
                        duration_seconds=duration,
                        inputs=request.inputs,
                    )
                )

                task_id = (
                    history_record.get(
                        "id"
                    )
                )

            except Exception as exc:

                log(
                    f"⚠️ History save failed: "
                    f"{exc}"
                )

        # ----------------------------------------------------
        # RESPONSE
        # ----------------------------------------------------

        return {

            "status": status,

            "task": request.task,

            "task_id": task_id,

            "plan": plan,

            "logs": get_logs(),

            "project_name": result.get(
                "project_name"
            ),

            "workspace_name": workspace_name,

            "project_url": project_url,

            "zip_url": zip_url,

            "result": result,

            "duration_seconds": round(
                duration,
                3,
            ),
        }

    except Exception as exc:

        duration = (
            time.perf_counter()
            - start_time
        )

        error_message = str(exc)

        log(
            f"❌ Agent error: "
            f"{error_message}"
        )

        # ----------------------------------------------------
        # ERROR HISTORY
        # ----------------------------------------------------

        if create_task_record:

            try:

                history_record = (
                    create_task_record(
                        task=request.task,
                        status="error",
                        plan=plan,
                        logs=get_logs(),
                        result={
                            "success": False,
                            "error": error_message,
                        },
                        generated_file=None,
                        duration_seconds=duration,
                        inputs=request.inputs,
                    )
                )

                task_id = (
                    history_record.get(
                        "id"
                    )
                )

            except Exception:
                pass

        return {

            "status": "error",

            "task": request.task,

            "task_id": task_id,

            "message": error_message,

            "logs": get_logs(),

            "duration_seconds": round(
                duration,
                3,
            ),
        }


# ============================================================
# PROJECT LIST
# ============================================================

@app.get("/projects")
def list_projects():

    PROJECTS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    projects = []

    for workspace in sorted(
        PROJECTS_DIR.iterdir(),
        key=lambda item: item.stat().st_mtime,
        reverse=True,
    ):

        if not workspace.is_dir():
            continue

        # ----------------------------------------------------
        # ONLY SHOW REAL PROJECT FILES
        # ----------------------------------------------------

        files = []

        for path in workspace.rglob("*"):

            if not path.is_file():
                continue

            relative = path.relative_to(
                workspace
            )

            if not is_displayable_project_file(
                relative
            ):
                continue

            files.append(
                relative.as_posix()
            )

        zip_path = (
            PROJECTS_DIR
            / f"{workspace.name}.zip"
        )

        projects.append({

            "workspace_name":
                workspace.name,

            "project_name": re.sub(
                r"\_[0-9a-f]{8}$",
                "",
                workspace.name,
            ),

            "file_count":
                len(files),

            "files":
                sorted(files),

            "zip_available":
                zip_path.exists(),

            "project_url":
                f"/projects/"
                f"{workspace.name}",

            "zip_url": (
                f"/download-project/"
                f"{workspace.name}"
                if zip_path.exists()
                else None
            ),
        })

    return {
        "count": len(projects),
        "projects": projects,
    }


# ============================================================
# PROJECT DETAILS
# ============================================================

@app.get(
    "/projects/{workspace_name}"
)
def project_details(
    workspace_name: str,
):

    workspace = (
        resolve_project_workspace(
            workspace_name
        )
    )

    if workspace is None:

        raise HTTPException(
            status_code=404,
            detail="Project not found.",
        )

    files = []

    for path in sorted(
        workspace.rglob("*")
    ):

        if not path.is_file():
            continue

        relative_path = (
            path.relative_to(
                workspace
            )
        )

        # ----------------------------------------------------
        # HIDE CACHE / BINARY FILES
        # ----------------------------------------------------

        if not is_displayable_project_file(
            relative_path
        ):
            continue

        relative = (
            relative_path.as_posix()
        )

        files.append({

            "path": relative,

            "view_url": (
                f"/projects/"
                f"{workspace_name}"
                f"/file/"
                f"{relative}"
            ),
        })

    zip_path = (
        PROJECTS_DIR
        / f"{workspace_name}.zip"
    )

    return {

        "workspace_name":
            workspace_name,

        "project_name": re.sub(
            r"\_[0-9a-f]{8}$",
            "",
            workspace_name,
        ),

        "files": files,

        "zip_available":
            zip_path.exists(),

        "zip_url": (
            f"/download-project/"
            f"{workspace_name}"
            if zip_path.exists()
            else None
        ),
    }


# ============================================================
# PROJECT FILE VIEW
# ============================================================

@app.get(
    "/projects/"
    "{workspace_name}/file/"
    "{file_path:path}"
)
def view_project_file(
    workspace_name: str,
    file_path: str,
):

    path = resolve_project_file(
        workspace_name,
        file_path,
    )

    if path is None:

        raise HTTPException(
            status_code=404,
            detail=(
                "Project file not found "
                "or file type is not "
                "available for preview."
            ),
        )

    # --------------------------------------------------------
    # BASIC BINARY PROTECTION
    # --------------------------------------------------------

    try:

        sample = path.read_bytes()[
            :4096
        ]

        if b"\x00" in sample:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Binary files cannot "
                    "be previewed."
                ),
            )

    except HTTPException:
        raise

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )

    return FileResponse(
        path=str(path),
        media_type="text/plain",
    )


# ============================================================
# PROJECT ZIP DOWNLOAD
# ============================================================

@app.get(
    "/download-project/"
    "{workspace_name}"
)
def download_project(
    workspace_name: str,
):

    zip_path = (
        resolve_project_zip(
            workspace_name
        )
    )

    if zip_path is None:

        raise HTTPException(
            status_code=404,
            detail="Project ZIP not found.",
        )

    return FileResponse(
        path=str(zip_path),
        filename=zip_path.name,
        media_type="application/zip",
    )


# ============================================================
# DELETE PROJECT
# ============================================================

@app.delete(
    "/projects/{workspace_name}"
)
def delete_project(
    workspace_name: str,
):

    workspace = (
        resolve_project_workspace(
            workspace_name
        )
    )

    if workspace is None:

        raise HTTPException(
            status_code=404,
            detail="Project not found.",
        )

    zip_path = (
        PROJECTS_DIR
        / f"{workspace_name}.zip"
    )

    try:

        shutil.rmtree(
            workspace
        )

        if zip_path.exists():
            zip_path.unlink()

        log(
            f"🗑️ Deleted project: "
            f"{workspace_name}"
        )

        return {

            "status": "success",

            "message":
                "Project deleted successfully.",

            "workspace_name":
                workspace_name,
        }

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )


# ============================================================
# LEGACY SINGLE-FILE VIEW
# ============================================================

@app.get(
    "/view/{filename}"
)
def view_generated_file(
    filename: str,
):

    file_path = get_generated_file(
        filename
    )

    if (
        file_path is None
        or not file_path.exists()
    ):

        raise HTTPException(
            status_code=404,
            detail=(
                "Generated file not found."
            ),
        )

    # Only expose readable legacy files.
    try:

        sample = file_path.read_bytes()[
            :4096
        ]

        if b"\x00" in sample:

            raise HTTPException(
                status_code=400,
                detail=(
                    "Binary files cannot "
                    "be previewed."
                ),
            )

    except HTTPException:
        raise

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )

    return FileResponse(
        path=str(file_path),
        media_type="text/plain",
    )


# ============================================================
# LEGACY SINGLE-FILE DOWNLOAD
# ============================================================

@app.get(
    "/download/{filename}"
)
def download_generated_file(
    filename: str,
):

    file_path = get_generated_file(
        filename
    )

    if (
        file_path is None
        or not file_path.exists()
    ):

        raise HTTPException(
            status_code=404,
            detail=(
                "Generated file not found."
            ),
        )

    return FileResponse(
        path=str(file_path),
        filename=file_path.name,
        media_type="text/x-python",
    )


# ============================================================
# LEGACY SINGLE-FILE DELETE
# ============================================================

@app.delete(
    "/generated-files/{filename}"
)
def delete_generated_file(
    filename: str,
):

    if not filename.endswith(
        ".py"
    ):

        raise HTTPException(
            status_code=400,
            detail=(
                "Only generated Python "
                "files can be deleted."
            ),
        )

    file_path = get_generated_file(
        filename
    )

    if (
        file_path is None
        or not file_path.exists()
    ):

        raise HTTPException(
            status_code=404,
            detail=(
                "Generated file not found."
            ),
        )

    try:

        deleted_name = file_path.name

        file_path.unlink()

        log(
            f"🗑️ Deleted generated file: "
            f"{deleted_name}"
        )

        return {

            "status": "success",

            "message":
                "Generated file deleted successfully.",

            "filename":
                deleted_name,
        }

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )


# ============================================================
# LEGACY SINGLE-FILE LIST
# ============================================================

@app.get(
    "/generated-files"
)
def list_generated_files():

    GENERATED_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    files = []

    for file in sorted(
        GENERATED_DIR.glob("*.py"),
        key=lambda item: item.stat().st_mtime,
        reverse=True,
    ):

        files.append({

            "name":
                file.name,

            "view_url":
                f"/view/{file.name}",

            "download_url":
                f"/download/{file.name}",

            "delete_url":
                f"/generated-files/"
                f"{file.name}",
        })

    return {

        "count":
            len(files),

        "files":
            files,
    }


# ============================================================
# HISTORY
# ============================================================

@app.get(
    "/history"
)
def task_history(
    limit: int = 50,
):

    if get_history is None:

        raise HTTPException(
            status_code=500,
            detail=(
                "History module is not available."
            ),
        )

    history = get_history(
        limit
    )

    return {

        "count":
            len(history),

        "tasks":
            history,
    }


# ============================================================
# SINGLE HISTORY RECORD
# ============================================================

@app.get(
    "/history/{task_id}"
)
def single_task_history(
    task_id: str,
):

    if get_task is None:

        raise HTTPException(
            status_code=500,
            detail=(
                "History module is not available."
            ),
        )

    task = get_task(
        task_id
    )

    if task is None:

        raise HTTPException(
            status_code=404,
            detail=(
                "Task history not found."
            ),
        )

    return task


# ============================================================
# DELETE HISTORY
# ============================================================

@app.delete(
    "/history"
)
def delete_task_history():

    if clear_history is None:

        raise HTTPException(
            status_code=500,
            detail=(
                "History module is not available."
            ),
        )

    clear_history()

    return {

        "status":
            "success",

        "message":
            "Task history cleared.",
    }